In [19]:
from sklearn.datasets import load_iris
import pandas as pd

In [2]:
data = load_iris()
# data.target[[10, 25, 50]]
# array([0, 0, 1])
# list(data.target_names)

In [4]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
df = load_iris(return_X_y=True, as_frame=True)

In [24]:
df_all = df[0]
df_all['y'] = df[1].values

In [44]:
df_all

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),y
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [43]:

convert_dict = {'y': str}
 
df_all = df_all.astype(convert_dict)

df_all.dtypes

TypeError: data type '' not understood

In [49]:
df_all

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),y
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [36]:
df_all.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
y                      int64
dtype: object

In [33]:
x=2.3
f'{x:.1f}'

'2.3'

In [31]:
str(3.2)

TypeError: 'str' object is not callable

In [48]:
df_all['y'].apply(str)

AttributeError: '' is not a valid function for 'Series' object

In [66]:
df_all.dtypes.values[0] == float

True

In [ ]:
[[#symbol("0"), #number(1), #number(2), #symbol("0")],
    [#symbol("0"), #number(2), #number(3), #symbol("0")],
    [#symbol("0"), #number(5), #number(4), #symbol("1")],
    [#symbol("0"), #number(8), #number(5), #symbol("1")],
    [#symbol("1"), #number(5), #number(2), #symbol("1")],
    [#symbol("1"), #number(6), #number(3), #symbol("1")],
    [#symbol("1"), #number(3), #number(4), #symbol("0")],
    [#symbol("1"), #number(4), #number(5), #symbol("0")]];

In [97]:
mystr = "["
for index, row in df_all.iterrows():
    mystr = mystr + "["
    for col in range(df_all.shape[1]):
        if df_all.dtypes.values[col] == float:
            mystr = mystr + "#number(" + f'{row[col]:.1f}' + ")"
        else:
            mystr = mystr + "#symbol(" + '\"' + f'{int(row[col])}' + '\"' + ")"
        if col < df_all.shape[1]-1:
            mystr = mystr + ", "
    mystr = mystr + "]"

    if index < df_all.shape[0]-1:
        mystr = mystr + ",\n"
mystr = mystr + "]"
print(mystr)

[[#number(5.1), #number(3.5), #number(1.4), #number(0.2), #symbol("0")],
[#number(4.9), #number(3.0), #number(1.4), #number(0.2), #symbol("0")],
[#number(4.7), #number(3.2), #number(1.3), #number(0.2), #symbol("0")],
[#number(4.6), #number(3.1), #number(1.5), #number(0.2), #symbol("0")],
[#number(5.0), #number(3.6), #number(1.4), #number(0.2), #symbol("0")],
[#number(5.4), #number(3.9), #number(1.7), #number(0.4), #symbol("0")],
[#number(4.6), #number(3.4), #number(1.4), #number(0.3), #symbol("0")],
[#number(5.0), #number(3.4), #number(1.5), #number(0.2), #symbol("0")],
[#number(4.4), #number(2.9), #number(1.4), #number(0.2), #symbol("0")],
[#number(4.9), #number(3.1), #number(1.5), #number(0.1), #symbol("0")],
[#number(5.4), #number(3.7), #number(1.5), #number(0.2), #symbol("0")],
[#number(4.8), #number(3.4), #number(1.6), #number(0.2), #symbol("0")],
[#number(4.8), #number(3.0), #number(1.4), #number(0.1), #symbol("0")],
[#number(4.3), #number(3.0), #number(1.1), #number(0.1), #symbol("0")],
[#number(5.8), #number(4.0), #number(1.2), #number(0.2), #symbol("0")],
[#number(5.7), #number(4.4), #number(1.5), #number(0.4), #symbol("0")],
[#number(5.4), #number(3.9), #number(1.3), #number(0.4), #symbol("0")],
[#number(5.1), #number(3.5), #number(1.4), #number(0.3), #symbol("0")],
[#number(5.7), #number(3.8), #number(1.7), #number(0.3), #symbol("0")],
[#number(5.1), #number(3.8), #number(1.5), #number(0.3), #symbol("0")],
[#number(5.4), #number(3.4), #number(1.7), #number(0.2), #symbol("0")],
[#number(5.1), #number(3.7), #number(1.5), #number(0.4), #symbol("0")],
[#number(4.6), #number(3.6), #number(1.0), #number(0.2), #symbol("0")],
[#number(5.1), #number(3.3), #number(1.7), #number(0.5), #symbol("0")],
[#number(4.8), #number(3.4), #number(1.9), #number(0.2), #symbol("0")],
[#number(5.0), #number(3.0), #number(1.6), #number(0.2), #symbol("0")],
[#number(5.0), #number(3.4), #number(1.6), #number(0.4), #symbol("0")],
[#number(5.2), #number(3.5), #number(1.5), #number(0.2), #symbol("0")],
[#number(5.2), #number(3.4), #number(1.4), #number(0.2), #symbol("0")],
[#number(4.7), #number(3.2), #number(1.6), #number(0.2), #symbol("0")],
[#number(4.8), #number(3.1), #number(1.6), #number(0.2), #symbol("0")],
[#number(5.4), #number(3.4), #number(1.5), #number(0.4), #symbol("0")],
[#number(5.2), #number(4.1), #number(1.5), #number(0.1), #symbol("0")],
[#number(5.5), #number(4.2), #number(1.4), #number(0.2), #symbol("0")],
[#number(4.9), #number(3.1), #number(1.5), #number(0.2), #symbol("0")],
[#number(5.0), #number(3.2), #number(1.2), #number(0.2), #symbol("0")],
[#number(5.5), #number(3.5), #number(1.3), #number(0.2), #symbol("0")],
[#number(4.9), #number(3.6), #number(1.4), #number(0.1), #symbol("0")],
[#number(4.4), #number(3.0), #number(1.3), #number(0.2), #symbol("0")],
[#number(5.1), #number(3.4), #number(1.5), #number(0.2), #symbol("0")],
[#number(5.0), #number(3.5), #number(1.3), #number(0.3), #symbol("0")],
[#number(4.5), #number(2.3), #number(1.3), #number(0.3), #symbol("0")],
[#number(4.4), #number(3.2), #number(1.3), #number(0.2), #symbol("0")],
[#number(5.0), #number(3.5), #number(1.6), #number(0.6), #symbol("0")],
[#number(5.1), #number(3.8), #number(1.9), #number(0.4), #symbol("0")],
[#number(4.8), #number(3.0), #number(1.4), #number(0.3), #symbol("0")],
[#number(5.1), #number(3.8), #number(1.6), #number(0.2), #symbol("0")],
[#number(4.6), #number(3.2), #number(1.4), #number(0.2), #symbol("0")],
[#number(5.3), #number(3.7), #number(1.5), #number(0.2), #symbol("0")],
[#number(5.0), #number(3.3), #number(1.4), #number(0.2), #symbol("0")],
[#number(7.0), #number(3.2), #number(4.7), #number(1.4), #symbol("1")],
[#number(6.4), #number(3.2), #number(4.5), #number(1.5), #symbol("1")],
[#number(6.9), #number(3.1), #number(4.9), #number(1.5), #symbol("1")],
[#number(5.5), #number(2.3), #number(4.0), #number(1.3), #symbol("1")],
[#number(6.5), #number(2.8), #number(4.6), #number(1.5), #symbol("1")],
[#number(5.7), #number(2.8), #number(4.5), #number(1.3), #symbol("1")],
[#number(6.3), #number(3.3), #number(4.7), #number(1.6), #symbol("1")],
[#number(4.9), #number(2.4), #number(3.3), #number(1.0), #symbol("1")],
[#number(6.6), #number(2.9), #number(4.6), #number(1.3), #symbol("1")],
[#number(5.2), #number(2.7), #number(3.9), #number(1.4), #symbol("1")],
[#number(5.0), #number(2.0), #number(3.5), #number(1.0), #symbol("1")],
[#number(5.9), #number(3.0), #number(4.2), #number(1.5), #symbol("1")],
[#number(6.0), #number(2.2), #number(4.0), #number(1.0), #symbol("1")],
[#number(6.1), #number(2.9), #number(4.7), #number(1.4), #symbol("1")],
[#number(5.6), #number(2.9), #number(3.6), #number(1.3), #symbol("1")],
[#number(6.7), #number(3.1), #number(4.4), #number(1.4), #symbol("1")],
[#number(5.6), #number(3.0), #number(4.5), #number(1.5), #symbol("1")],
[#number(5.8), #number(2.7), #number(4.1), #number(1.0), #symbol("1")],
[#number(6.2), #number(2.2), #number(4.5), #number(1.5), #symbol("1")],
[#number(5.6), #number(2.5), #number(3.9), #number(1.1), #symbol("1")],
[#number(5.9), #number(3.2), #number(4.8), #number(1.8), #symbol("1")],
[#number(6.1), #number(2.8), #number(4.0), #number(1.3), #symbol("1")],
[#number(6.3), #number(2.5), #number(4.9), #number(1.5), #symbol("1")],
[#number(6.1), #number(2.8), #number(4.7), #number(1.2), #symbol("1")],
[#number(6.4), #number(2.9), #number(4.3), #number(1.3), #symbol("1")],
[#number(6.6), #number(3.0), #number(4.4), #number(1.4), #symbol("1")],
[#number(6.8), #number(2.8), #number(4.8), #number(1.4), #symbol("1")],
[#number(6.7), #number(3.0), #number(5.0), #number(1.7), #symbol("1")],
[#number(6.0), #number(2.9), #number(4.5), #number(1.5), #symbol("1")],
[#number(5.7), #number(2.6), #number(3.5), #number(1.0), #symbol("1")],
[#number(5.5), #number(2.4), #number(3.8), #number(1.1), #symbol("1")],
[#number(5.5), #number(2.4), #number(3.7), #number(1.0), #symbol("1")],
[#number(5.8), #number(2.7), #number(3.9), #number(1.2), #symbol("1")],
[#number(6.0), #number(2.7), #number(5.1), #number(1.6), #symbol("1")],
[#number(5.4), #number(3.0), #number(4.5), #number(1.5), #symbol("1")],
[#number(6.0), #number(3.4), #number(4.5), #number(1.6), #symbol("1")],
[#number(6.7), #number(3.1), #number(4.7), #number(1.5), #symbol("1")],
[#number(6.3), #number(2.3), #number(4.4), #number(1.3), #symbol("1")],
[#number(5.6), #number(3.0), #number(4.1), #number(1.3), #symbol("1")],
[#number(5.5), #number(2.5), #number(4.0), #number(1.3), #symbol("1")],
[#number(5.5), #number(2.6), #number(4.4), #number(1.2), #symbol("1")],
[#number(6.1), #number(3.0), #number(4.6), #number(1.4), #symbol("1")],
[#number(5.8), #number(2.6), #number(4.0), #number(1.2), #symbol("1")],
[#number(5.0), #number(2.3), #number(3.3), #number(1.0), #symbol("1")],
[#number(5.6), #number(2.7), #number(4.2), #number(1.3), #symbol("1")],
[#number(5.7), #number(3.0), #number(4.2), #number(1.2), #symbol("1")],
[#number(5.7), #number(2.9), #number(4.2), #number(1.3), #symbol("1")],
[#number(6.2), #number(2.9), #number(4.3), #number(1.3), #symbol("1")],
[#number(5.1), #number(2.5), #number(3.0), #number(1.1), #symbol("1")],
[#number(5.7), #number(2.8), #number(4.1), #number(1.3), #symbol("1")],
[#number(6.3), #number(3.3), #number(6.0), #number(2.5), #symbol("2")],
[#number(5.8), #number(2.7), #number(5.1), #number(1.9), #symbol("2")],
[#number(7.1), #number(3.0), #number(5.9), #number(2.1), #symbol("2")],
[#number(6.3), #number(2.9), #number(5.6), #number(1.8), #symbol("2")],
[#number(6.5), #number(3.0), #number(5.8), #number(2.2), #symbol("2")],
[#number(7.6), #number(3.0), #number(6.6), #number(2.1), #symbol("2")],
[#number(4.9), #number(2.5), #number(4.5), #number(1.7), #symbol("2")],
[#number(7.3), #number(2.9), #number(6.3), #number(1.8), #symbol("2")],
[#number(6.7), #number(2.5), #number(5.8), #number(1.8), #symbol("2")],
[#number(7.2), #number(3.6), #number(6.1), #number(2.5), #symbol("2")],
[#number(6.5), #number(3.2), #number(5.1), #number(2.0), #symbol("2")],
[#number(6.4), #number(2.7), #number(5.3), #number(1.9), #symbol("2")],
[#number(6.8), #number(3.0), #number(5.5), #number(2.1), #symbol("2")],
[#number(5.7), #number(2.5), #number(5.0), #number(2.0), #symbol("2")],
[#number(5.8), #number(2.8), #number(5.1), #number(2.4), #symbol("2")],
[#number(6.4), #number(3.2), #number(5.3), #number(2.3), #symbol("2")],
[#number(6.5), #number(3.0), #number(5.5), #number(1.8), #symbol("2")],
[#number(7.7), #number(3.8), #number(6.7), #number(2.2), #symbol("2")],
[#number(7.7), #number(2.6), #number(6.9), #number(2.3), #symbol("2")],
[#number(6.0), #number(2.2), #number(5.0), #number(1.5), #symbol("2")],
[#number(6.9), #number(3.2), #number(5.7), #number(2.3), #symbol("2")],
[#number(5.6), #number(2.8), #number(4.9), #number(2.0), #symbol("2")],
[#number(7.7), #number(2.8), #number(6.7), #number(2.0), #symbol("2")],
[#number(6.3), #number(2.7), #number(4.9), #number(1.8), #symbol("2")],
[#number(6.7), #number(3.3), #number(5.7), #number(2.1), #symbol("2")],
[#number(7.2), #number(3.2), #number(6.0), #number(1.8), #symbol("2")],
[#number(6.2), #number(2.8), #number(4.8), #number(1.8), #symbol("2")],
[#number(6.1), #number(3.0), #number(4.9), #number(1.8), #symbol("2")],
[#number(6.4), #number(2.8), #number(5.6), #number(2.1), #symbol("2")],
[#number(7.2), #number(3.0), #number(5.8), #number(1.6), #symbol("2")],
[#number(7.4), #number(2.8), #number(6.1), #number(1.9), #symbol("2")],
[#number(7.9), #number(3.8), #number(6.4), #number(2.0), #symbol("2")],
[#number(6.4), #number(2.8), #number(5.6), #number(2.2), #symbol("2")],
[#number(6.3), #number(2.8), #number(5.1), #number(1.5), #symbol("2")],
[#number(6.1), #number(2.6), #number(5.6), #number(1.4), #symbol("2")],
[#number(7.7), #number(3.0), #number(6.1), #number(2.3), #symbol("2")],
[#number(6.3), #number(3.4), #number(5.6), #number(2.4), #symbol("2")],
[#number(6.4), #number(3.1), #number(5.5), #number(1.8), #symbol("2")],
[#number(6.0), #number(3.0), #number(4.8), #number(1.8), #symbol("2")],
[#number(6.9), #number(3.1), #number(5.4), #number(2.1), #symbol("2")],
[#number(6.7), #number(3.1), #number(5.6), #number(2.4), #symbol("2")],
[#number(6.9), #number(3.1), #number(5.1), #number(2.3), #symbol("2")],
[#number(5.8), #number(2.7), #number(5.1), #number(1.9), #symbol("2")],
[#number(6.8), #number(3.2), #number(5.9), #number(2.3), #symbol("2")],
[#number(6.7), #number(3.3), #number(5.7), #number(2.5), #symbol("2")],
[#number(6.7), #number(3.0), #number(5.2), #number(2.3), #symbol("2")],
[#number(6.3), #number(2.5), #number(5.0), #number(1.9), #symbol("2")],
[#number(6.5), #number(3.0), #number(5.2), #number(2.0), #symbol("2")],
[#number(6.2), #number(3.4), #number(5.4), #number(2.3), #symbol("2")],
[#number(5.9), #number(3.0), #number(5.1), #number(1.8), #symbol("2")]]